Notes on the lecture about "Intro to Julia"

In [9]:
x = 5.3 # not "x equals 5.3" but, "assign x to be 5.3"

5.3

assignment is not the same as "equals"!

In [10]:
x == 5.3

true

In [11]:
println("hello,world!") ## "ln" is for "line" to creat a new line afterwards.

hello,world!


In [12]:
println("What is x? ", x)

What is x? 5.3


### Types

x is represented on your computer using a chuck of memory consisting of 64 bits (bit = binary digit). It is represented in the double-precision floating point format.

In [13]:
typeof(x) # This function returns the data type of the object

Float64

In [14]:
y = 5
typeof(y)

Int64

In [15]:
my_name = "Alan"
typeof(my_name)

String

the Symbol is an interned string, which makes e.g. string comparison operations faster.

In [16]:
my_name = :Alan
typeof(my_name)

Symbol

In [17]:
typeof(true)

Bool

### Dictionaries

In [18]:
atomic_mass = Dict{Symbol, Float64}(:C => 12.01, :N => 14.0067, :O => 15.999, :H => 1.01)

Dict{Symbol, Float64} with 4 entries:
  :N => 14.0067
  :H => 1.01
  :O => 15.999
  :C => 12.01

note the order is not the same as when we constructed the dictionary... so never assume the dictionary is in a certain order. for ordered elements just use an Array

querying a dictionary via passing the key, returning the value

In [19]:
atomic_mass[:C]

12.01

add a (key, value) pair to a dictionary

In [20]:
atomic_mass[:Fe] = 55.845
atomic_mass

Dict{Symbol, Float64} with 5 entries:
  :N  => 14.0067
  :Fe => 55.845
  :H  => 1.01
  :O  => 15.999
  :C  => 12.01

You can also change the value of a key in the dictionary. 

In [21]:
atomic_mass[:H] = 1.008
atomic_mass

Dict{Symbol, Float64} with 5 entries:
  :N  => 14.0067
  :Fe => 55.845
  :H  => 1.008
  :O  => 15.999
  :C  => 12.01

In [22]:
for (element, mass) in atomic_mass # iterate over, unpack the (key, value) pairs
    print("the atomic mass of ")
    print(element)
    println(" is ", mass)
end

the atomic mass of N is 14.0067
the atomic mass of Fe is 55.845
the atomic mass of H is 1.008
the atomic mass of O is 15.999
the atomic mass of C is 12.01


what are the keys? what are the values?



In [23]:
keys(atomic_mass)

KeySet for a Dict{Symbol, Float64} with 5 entries. Keys:
  :N
  :Fe
  :H
  :O
  :C

In [24]:
values(atomic_mass)

ValueIterator for a Dict{Symbol, Float64} with 5 entries. Values:
  14.0067
  55.845
  1.008
  15.999
  12.01

### Arrays

In [25]:
x = [6.3, 1.2, 8.2, 10.8]

4-element Vector{Float64}:
  6.3
  1.2
  8.2
 10.8

In [30]:
x[3] = 43.0 # Change the third element. Julia indexes on the 1. Just like matlab
x

4-element Vector{Float64}:
  6.3
  1.2
 43.0
 10.8

### Iterating through an array

In [33]:
# (1) iterating through indices of the array 1,2,...,length(x)
for i = 1:length(x)
    println("x[$i] = ", x[i])
end

# (2) directly iterating through the elements
println("entries are: ")
for element in x
    println("  ", element)
end

# (3) iterating through both the indices and the elements
for (i, ele) in enumerate(x)
    println("x[$i] = $ele")
end

x[1] = 6.3
x[2] = 1.2
x[3] = 43.0
x[4] = 10.8
entries are: 
  6.3
  1.2
  43.0
  10.8
x[1] = 6.3
x[2] = 1.2
x[3] = 43.0
x[4] = 10.8


### Adding elements to an array
This is similar to python's built in function, append

In [34]:
push!(x,23.0) # exclamation means function will modify its argument

5-element Vector{Float64}:
  6.3
  1.2
 43.0
 10.8
 23.0

Let's push x to the front of the array

In [35]:
pushfirst!(x, 0.0)
x

6-element Vector{Float64}:
  0.0
  6.3
  1.2
 43.0
 10.8
 23.0

### Slicing
by indicies (by Arrays of Int64s)

In [37]:
ids_i_want = [2, 6]

println("x = ", x) # Print the original x array
println("x[ids_i_want] = ", x[ids_i_want]) # Prints the values of the second and sixth indices

x = [0.0, 6.3, 1.2, 43.0, 10.8, 23.0]
x[ids_i_want] = [6.3, 23.0]


In [39]:
x[2:3] # slice the array from the second to the third element (inclusive)

2-element Vector{Float64}:
 6.3
 1.2

In [40]:
x[2:end] # slice the array from the second the the last element (inclusive)

5-element Vector{Float64}:
  6.3
  1.2
 43.0
 10.8
 23.0

by specifying whether or not (true/false) we want to keep each element (by Arrays of Bools)
this way of slicing is especially useful for selecting certain elements of an array that obey a certain condition

In [42]:
keep_entry = [true, false, false, false, false, true]

println("x = ", x)
println("x[keep_entry] = ", x[keep_entry]) # Only prints the first and last element since those are try in the `keep_entry` array

x = [0.0, 6.3, 1.2, 43.0, 10.8, 23.0]
x[keep_entry] = [0.0, 23.0]


e.g., lets get all array elements that are greater than 12

In [43]:
x > 12.0 # "is this vector greater than this number?" makes no sense.


LoadError: MethodError: no method matching isless(::Float64, ::Vector{Float64})
The function `isless` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  isless(::Missing, ::Any)
   @ Base missing.jl:87
  isless(::Any, ::Missing)
   @ Base missing.jl:88
  isless(::T, ::T) where T<:Union{Float16, Float32, Float64}
   @ Base float.jl:630
  ...


In [44]:
x .> 12.0 # elementwise [array of bits is similar to array of bools]


6-element BitVector:
 0
 0
 0
 1
 0
 1

If we want to pull these values, we can do a bit of tweaking to the previous cell

In [45]:
x[x .> 12.0]


2-element Vector{Float64}:
 43.0
 23.0

### Multi-dimensional arrays

In [46]:
y = [1 3 1;
     0 8 3]

2×3 Matrix{Int64}:
 1  3  1
 0  8  3

In [48]:
size(y)

(2, 3)

In [50]:
y[:,2]

2-element Vector{Int64}:
 3
 8

In [52]:
y[1,3] = 400 # Changing the element 
y

2×3 Matrix{Int64}:
 1  3  400
 0  8    3

### Constructing an array
without manually typing out its elements 

In [53]:
# (1) list comprehnsion (fast, beautiful)
x = [2.0 * i for i = 1:5] # think "what do I want in element i?"

# (2) pre-allocate memory, fill in (fast, takes a few lines)
x = zeros(Float64, 5) # construct a 5-element array with zeros
for i = 1:5
    x[i] = 2 * i
end

# (3) start with empty array, add values (slow)
x = Float64[]
for i = 1:5
    push!(x, 2 * i)
end
x

5-element Vector{Float64}:
  2.0
  4.0
  6.0
  8.0
 10.0

### Operations on arrays
precede with . to indicate element-wise

In [57]:
x = [0.0, 1.0, 2.0]
y = [5.0, 6.0, 7.0]

x.*y

3-element Vector{Float64}:
  0.0
  6.0
 14.0

In [59]:
x .+ y

3-element Vector{Float64}:
 5.0
 7.0
 9.0

In [60]:
sin.(x)

3-element Vector{Float64}:
 0.0
 0.8414709848078965
 0.9092974268256817

In [62]:
A = rand(3,3)

3×3 Matrix{Float64}:
 0.194764  0.234025  0.0894094
 0.4738    0.970849  0.553748
 0.5683    0.227752  0.179573

In [63]:
A *x 

3-element Vector{Float64}:
 0.41284373013383424
 2.0783440830468476
 0.5868970430648129

### Create your own data structure

In [64]:
struct Molecule
    species::Symbol
    atoms::Array{Symbol}
end

molecule = Molecule(:methane, [:C,:H, :H, :H, :H])

Molecule(:methane, [:C, :H, :H, :H, :H])

In [65]:
molecule.species # pull the attributes

:methane

### Functions